/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.1.9-dev at Thu Jun  6 18:30:29 2013. */

#include "firmware.pb.h"



const pb_field_t firmware_Firmware_fields[4] = {
    {10, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    offsetof(firmware_Firmware, target), 0,
    pb_membersize(firmware_Firmware, target), 0, 0},

    {20, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(firmware_Firmware, crc, target), 0,
    pb_membersize(firmware_Firmware, crc), 0, 0},

    {30, (pb_type_t) ((int) PB_HTYPE_CALLBACK | (int) PB_LTYPE_BYTES),
    pb_delta_end(firmware_Firmware, hex, crc), 0,
    pb_membersize(firmware_Firmware, hex), 0, 0},

    PB_LAST_FIELD
};

const pb_field_t firmware_Update_fields[3] = {
    {10, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    offsetof(firmware_Update, method), 0,
    pb_membersize(firmware_Update, method), 0, 0},

    {20, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(firmware_Update, crc, method), 0,
    pb_membersize(firmware_Update, crc), 0, 0},

    PB_LAST_FIELD
};

const pb_field_t firmware_Response_fields[3] = {
    {10, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    offsetof(firmware_Response, status), 0,
    pb_membersize(firmware_Response, status), 0, 0},

    {20, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(firmware_Response, errorCode, status),
    pb_delta(firmware_Response, has_errorCode, errorCode),
    pb_membersize(firmware_Response, errorCode), 0, 0},

    PB_LAST_FIELD
};

