/* Automatically generated nanopb header */
/* Generated by nanopb-0.1.9-dev at Wed Apr 10 12:01:54 2013. */

#ifndef _PB_GPIO_PB_H_
#define _PB_GPIO_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
  #endif

  /* Enum definitions */
  /* Struct definitions */
  typedef struct _gpio_State {
    bool has_IO_DAC0;
    bool IO_DAC0;
    bool has_IO_DAC1;
    bool IO_DAC1;
  } gpio_State;

  /* Default values for struct fields */

  /* Struct field encoding specification for nanopb */
  extern const pb_field_t gpio_State_fields[3];

  #ifdef __cplusplus
} /* extern "C" */
#endif

#endif
