/* Automatically generated nanopb header */
/* Generated by nanopb-0.1.9-dev at Fri May 24 15:25:36 2013. */

#ifndef _PB_IOP_PB_H_
#define _PB_IOP_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct {
    size_t size;
    uint8_t bytes[16];
} iop_Envelope_iv_t;

typedef struct {
    size_t size;
    uint8_t bytes[20];
} iop_Envelope_hash_t;

typedef struct _iop_Envelope {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_src;
    uint64_t src;
    bool has_dst;
    uint64_t dst;
    uint64_t msgCode;
    bool has_nonce;
    uint64_t nonce;
    bool has_iv;
    iop_Envelope_iv_t iv;
    bool has_hash;
    iop_Envelope_hash_t hash;
    pb_callback_t msg;
} iop_Envelope;

/* Default values for struct fields */

/* Struct field encoding specification for nanopb */
extern const pb_field_t iop_Envelope_fields[9];

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
