/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.1.9-dev at Fri May 24 15:25:36 2013. */

#include "iop.pb.h"



const pb_field_t iop_Envelope_fields[9] = {
    {10, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    offsetof(iop_Envelope, timestamp),
    pb_delta(iop_Envelope, has_timestamp, timestamp),
    pb_membersize(iop_Envelope, timestamp), 0, 0},

    {20, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(iop_Envelope, src, timestamp),
    pb_delta(iop_Envelope, has_src, src),
    pb_membersize(iop_Envelope, src), 0, 0},

    {30, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(iop_Envelope, dst, src),
    pb_delta(iop_Envelope, has_dst, dst),
    pb_membersize(iop_Envelope, dst), 0, 0},

    {40, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(iop_Envelope, msgCode, dst), 0,
    pb_membersize(iop_Envelope, msgCode), 0, 0},

    {50, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_VARINT),
    pb_delta_end(iop_Envelope, nonce, msgCode),
    pb_delta(iop_Envelope, has_nonce, nonce),
    pb_membersize(iop_Envelope, nonce), 0, 0},

    {60, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_BYTES),
    pb_delta_end(iop_Envelope, iv, nonce),
    pb_delta(iop_Envelope, has_iv, iv),
    pb_membersize(iop_Envelope, iv), 0, 0},

    {70, (pb_type_t) ((int) PB_HTYPE_OPTIONAL | (int) PB_LTYPE_BYTES),
    pb_delta_end(iop_Envelope, hash, iv),
    pb_delta(iop_Envelope, has_hash, hash),
    pb_membersize(iop_Envelope, hash), 0, 0},

    {100, (pb_type_t) ((int) PB_HTYPE_CALLBACK | (int) PB_LTYPE_BYTES),
    pb_delta_end(iop_Envelope, msg, hash), 0,
    pb_membersize(iop_Envelope, msg), 0, 0},

    PB_LAST_FIELD
};

