/* Automatically generated nanopb header */
/* Generated by nanopb-0.1.9-dev at Fri Jan 18 14:24:39 2013. */

#ifndef _PB_NODE_PB_H_
#define _PB_NODE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _node_In {
    bool has_transferInterval;
    uint32_t transferInterval;
    bool has_leds;
    uint32_t leds;
    bool has_pollingInterval;
    uint32_t pollingInterval;
    bool has_timeout;
    uint32_t timeout;
    bool has_noOfPolls;
    uint32_t noOfPolls;
} node_In;

typedef struct _node_Out {
    bool has_batteryLevel;
    uint32_t batteryLevel;
    bool has_temperature;
    int32_t temperature;
} node_Out;

/* Default values for struct fields */

/* Struct field encoding specification for nanopb */
extern const pb_field_t node_Out_fields[3];
extern const pb_field_t node_In_fields[6];

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
